WITH MEM AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)

SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE 
FROM MEMBER_PROFILE P RIGHT JOIN REST_REVIEW R USING (MEMBER_ID)
WHERE R.MEMBER_ID = (SELECT * FROM MEM)
ORDER BY 3, 2