WITH U AS (
    SELECT USER_ID
    FROM USER_INFO 
    WHERE JOINED LIKE '2021%'
)

SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT USER_ID) PUCHASED_USERS, ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM U),1) PUCHASED_RATIO
FROM ONLINE_SALE 
WHERE USER_ID IN (SELECT * FROM U)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY 1, 2