WITH ALL_ORDER AS (SELECT FLAVOR, SUM(JULY.TOTAL_ORDER)+SUM(FIRST_HALF.TOTAL_ORDER) AS TOTAL
FROM FIRST_HALF
JOIN JULY USING (FLAVOR) 
GROUP BY FLAVOR)

SELECT FLAVOR
FROM ALL_ORDER
ORDER BY TOTAL DESC
LIMIT 3