WITH CAR AS 
    (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) BETWEEN '8' AND '10'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5)  
# 기간동안 빌린 횟수가 5회 이상인 CAR_ID 모음
SELECT 
    CASE WHEN MONTH(START_DATE) = 8 THEN 8
        WHEN MONTH(START_DATE) = 9 THEN 9
        WHEN MONTH(START_DATE) = 10 THEN 10
    END AS MONTH, 
    CAR_ID, 
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID FROM CAR) AND MONTH(START_DATE) BETWEEN '8' AND '10'
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH, CAR_ID DESC;