WITH RECURSIVE TIMES AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TIMES
    WHERE HOUR < 23
)

SELECT TIMES.HOUR HOUR, CASE WHEN ANIMAL_ID != '' THEN COUNT(*) ELSE 0 END COUNT
FROM ANIMAL_OUTS A
RIGHT JOIN TIMES ON HOUR(A.DATETIME) = TIMES.HOUR
GROUP BY 1
ORDER BY 1
