SELECT TITLE, BOARD.BOARD_ID, REPLY.REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d')
FROM USED_GOODS_BOARD as BOARD, USED_GOODS_REPLY as REPLY
WHERE BOARD.CREATED_DATE LIKE '2022-10%' AND BOARD.BOARD_ID = REPLY.BOARD_ID
ORDER BY REPLY.CREATED_DATE ASC, TITLE ASC